import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-transparent`}>
        <header className="flex items-center justify-between max-w-[1440px] m-[auto] py-[30px] px-[100px]">
          <img src="/logo.svg" alt="busnises" />
          <div className="flex items-center justify-between gap-12">
            <Navigation navlinks={[{ title: 'Home', href: '/' }, { title: 'About', href: '/about' }, { title: 'Services', href: '/servic' }, { title: 'System', href: '/system' }]} />
            <button className="border-solid border-2 border-[#6610F2] py-[10px] px-[20px] text-[#6610F2] rounded-[150px]">Contact Us</button>
          </div>
        </header>
        <main className="max-w-[1440px] m-[auto] mb-[80px]" >
          {children}
        </main>
       <Footer/>
      </body>
    </html>
  );
}
